### PR TITLE
Updated to RabbitMQ 3.5

### PR DESCRIPTION
**Pull request by dtretyakov**
Updated nuget packages. It'd be great to publish updated NLog.RabbitMQ package.

### CODE REVIEW

**Comment by haf** [comment]
@dtretyakov currently this PR has broken the build:

```
xbuild /verbosity:minimal src/NLog.Targets.RabbitMQ.sln
XBuild Engine Version 12.0
Mono, Version 3.12.1.0
Copyright (C) 2005-2013 Various Mono authors
		Configuration: Debug Platform: AnyCPU
RabbitMQ.cs(334,16): error CS0103: The name `Constants' does not exist in the current context
RabbitMQ.cs(380,15): error CS0246: The type or namespace name `BasicProperties' could not be found. Are you missing `RabbitMQ.Client.Framing.v0_8' or `RabbitMQ.Client.Framing.v0_9' or `RabbitMQ.Client.Framing.v0_8qpid' or `RabbitMQ.Client.Impl' using directive?
RabbitMQ.cs(477,29): error CS0103: The name `Constants' does not exist in the current context
RabbitMQ.cs(506,61): error CS0103: The name `Constants' does not exist in the current context
Configuration: Debug Platform: AnyCPU
Program.cs(168,11): error CS1061: Type `RabbitMQ.Client.IModel' does not contain a definition for `ExchangeDeclarePassive' and no extension method `ExchangeDeclarePassive' of type `RabbitMQ.Client.IModel' could be found. Are you missing an assembly reference?
/Library/Frameworks/Mono.framework/Versions/3.12.1/lib/mono/4.0/RabbitMQ.Client.dll (Location of the symbol related to previous error)
Program.cs(175,21): error CS1501: No overload for method `QueueDeclare' takes `5' arguments
/Library/Frameworks/Mono.framework/Versions/3.12.1/lib/mono/4.0/RabbitMQ.Client.dll (Location of the symbol related to previous error)
Program.cs(183,14): error CS1501: No overload for method `QueueDeclare' takes `5' arguments
/Library/Frameworks/Mono.framework/Versions/3.12.1/lib/mono/4.0/RabbitMQ.Client.dll (Location of the symbol related to previous error)
Program.cs(188,14): error CS1501: No overload for method `QueueDeclare' takes `5' arguments
/Library/Frameworks/Mono.framework/Versions/3.12.1/lib/mono/4.0/RabbitMQ.Client.dll (Location of the symbol related to previous error)
Program.cs(192,11): error CS1501: No overload for method `QueueBind' takes `3' arguments
/Library/Frameworks/Mono.framework/Versions/3.12.1/lib/mono/4.0/RabbitMQ.Client.dll (Location of the symbol related to previous error)
Program.cs(201,12): error CS1501: No overload for method `QueueDelete' takes `1' arguments
/Library/Frameworks/Mono.framework/Versions/3.12.1/lib/mono/4.0/RabbitMQ.Client.dll (Location of the symbol related to previous error)
Program.cs(239,25): error CS1502: The best overloaded method match for `RabbitMQ.Util.SharedQueue.Dequeue(int, out object)' has some invalid arguments
/Library/Frameworks/Mono.framework/Versions/3.12.1/lib/mono/4.0/RabbitMQ.Client.dll (Location of the symbol related to previous error)
Program.cs(239,42): error CS1503: Argument `#2' cannot convert `out RabbitMQ.Client.Events.BasicDeliverEventArgs' expression to type `out object'
rake aborted!
Albacore::CommandFailedError: Command failed with status (1):
  xbuild /verbosity:minimal src/NLog.Targets.RabbitMQ.sln
XBuild Engine Version 12.0
Mono, Version 3.12.1.0
Copyright (C) 2005-2013 Various Mono authors
		Configuration: Debug Platform: AnyCPU
RabbitMQ.cs(334,16): error CS0103: The name `Constants' does not exist in the current context
RabbitMQ.cs(380,15): error CS0246: The type or namespace name `BasicProperties' could not be found. Are you missing `RabbitMQ.Client.Framing.v0_8' or `RabbitMQ.Client.Framing.v0_9' or `RabbitMQ.Client.Framing.v0_8qpid' or `RabbitMQ.Client.Impl' using directive?
RabbitMQ.cs(477,29): error CS0103: The name `Constants' does not exist in the current context
RabbitMQ.cs(506,61): error CS0103: The name `Constants' does not exist in the current context
Configuration: Debug Platform: AnyCPU
Program.cs(168,11): error CS1061: Type `RabbitMQ.Client.IModel' does not contain a definition for `ExchangeDeclarePassive' and no extension method `ExchangeDeclarePassive' of type `RabbitMQ.Client.IModel' could be found. Are you missing an assembly reference?
/Library/Frameworks/Mono.framework/Versions/3.12.1/lib/mono/4.0/RabbitMQ.Client.dll (Location of the symbol related to previous error)
Program.cs(175,21): error CS1501: No overload for method `QueueDeclare' takes `5' arguments
/Library/Frameworks/Mono.framework/Versions/3.12.1/lib/mono/4.0/RabbitMQ.Client.dll (Location of the symbol related to previous error)
Program.cs(183,14): error CS1501: No overload for method `QueueDeclare' takes `5' arguments
/Library/Frameworks/Mono.framework/Versions/3.12.1/lib/mono/4.0/RabbitMQ.Client.dll (Location of the symbol related to previous error)
Program.cs(188,14): error CS1501: No overload for method `QueueDeclare' takes `5' arguments
/Library/Frameworks/Mono.framework/Versions/3.12.1/lib/mono/4.0/RabbitMQ.Client.dll (Location of the symbol related to previous error)
Program.cs(192,11): error CS1501: No overload for method `QueueBind' takes `3' arguments
/Library/Frameworks/Mono.framework/Versions/3.12.1/lib/mono/4.0/RabbitMQ.Client.dll (Location of the symbol related to previous error)
Program.cs(201,12): error CS1501: No overload for method `QueueDelete' takes `1' arguments
/Library/Frameworks/Mono.framework/Versions/3.12.1/lib/mono/4.0/RabbitMQ.Client.dll (Location of the symbol related to previous error)
Program.cs(239,25): error CS1502: The best overloaded method match for `RabbitMQ.Util.SharedQueue.Dequeue(int, out object)' has some invalid arguments
/Library/Frameworks/Mono.framework/Versions/3.12.1/lib/mono/4.0/RabbitMQ.Client.dll (Location of the symbol related to previous error)
Program.cs(239,42): error CS1503: Argument `#2' cannot convert `out RabbitMQ.Client.Events.BasicDeliverEventArgs' expression to type `out object'

Tasks: TOP => release => release:info => create_nugets => compile
(See full trace by running task with --trace)
```

Will you please send a new PR fixing the compiler errors, or I will revert this one?

**Comment by dtretyakov** [comment]
Ok, in this case it's better to upgrade packages at your own solution and reject this PR.

**Comment by haf** [comment]
I'm not actively maintaining this; I would suggest you send a PR to Logary and shift your usage towards that framework, in this case.

**Comment by dtretyakov** [comment]
Henrik, thanks for advice.

**Pull request merged**
