### PR TITLE
Hack for compatibility RabbitMQ.Client library between 3.4.x and 3.5.…

### PR DESCRIPTION
**Pull request by atagirov**
I wrote add delegate for ConnectionShutdown event using reflection.
This allow using both version of RabbitMQ.Client library 3.4.x and 3.5.x

I don't know how much is a good solution...

issue #22

### CODE REVIEW

**Comment by haf** [comment]
Tested? Works?

**Comment by atagirov** [comment]
after second commit must work (also tested lost of connection - in 3.5.x version removed ShutdownEventArgs constructors without cause parameter)

**Comment by atagirov** [comment]
I build project with RabbitMQ.Client v. 3.4.0, after testing in aplications what using:
- RabitMQ.Client v. 3.4.0
- RabitMQ.Client v. 3.5.2
- RabitMQ.Client v. 3.5.3

during testing i also change password property of target to incorrect, for check "ConnectionShutdown" logic (and catch error, what fixed by second commit), also i switch off rabbit server, for check "ConnectionShutdown" by TimeoutException.

**Comment by atagirov** [comment]
using reflection just once - in constructor (some performance)
added comments for describe why we are doing this.

it's last commits by this pull request ;)

**Comment by haf** [comment]
Nice, thank you @atagirov

**Comment by haf** [comment]
Pushed v2.2.1.

**Pull request merged**
