### PR TITLE
I updated the client to latest

### PR DESCRIPTION
**Pull request by SenyaMur**

### CODE REVIEW

**Comment by haf** [comment]
@SenyaMur THank you!

**Comment by SenyaMur** [comment]
@haf  Please, put new version in nuget

**Comment by bertvansteen** [comment]
@haf  Do  you want to update the NuGet package so it supports RabbitMQ 3.6.x? 
My app has a dependency on MassTransit.RabbitMQ and they don't support RabbitMQ 3.5.x anymore so I need to update NLog.RabbitMQ.

**Comment by haf** [comment]
@bertvansteen Ok, I push and perhaps meanwhile you can check out [qvitoo](https://qvitoo.com/?utm_source=github&utm_campaign=repos) and tell me possible improvements to our web site. :)

**Comment by bertvansteen** [comment]
;-) 
btw here is some information about the breaking change in 3.6.0, apparently they dropped the immediate flag: https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/98

**Comment by haf** [comment]
I've pushed the latest version, PR if they've broken their API in a minor release and I'll merge/release again. And thanks for the awesome comments.

**Pull request merged**
